services:
  isapre-landing:
    build: .
    container_name: opcion-isapre
    ports:
      - "8080:8080"  # Cambiado para que coincida con el puerto de Astro/Cloud Run
    volumes:
      - ./src/content:/app/src/content
      - ./public/images:/app/public/images
      # Añadimos el .env para que Keystatic tenga las llaves de GitHub en tu local
      - ./.env:/app/.env 
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=0.0.0.0